name: Smooth Secrets
description: Plugin to manage your secrets
author: https://github.com/hasura
requirements: []
configuration:
  properties:
    secrets:
      type: array
      items:
        type: object
        properties:
          strategy:
            type: string
          key:
            type: string
          type:
            type: string
          name:
            type: string
          file_path_env:
            type: string
          region:
            type: string
          encoding:
            type: string
        required:
          - strategy
          - key
          - type
          - region
  required:
    - secrets
  additionalProperties: false
